# Render blueprint for SatpamBot
# Docs: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: satpambot-web
    env: docker
    dockerfilePath: ./Dockerfile
    # If your Dockerfile needs a specific context or build args, add them here
    # buildCommand: ""
    # startCommand: "python main.py"  # usually not needed for docker env
    autoDeploy: true
    healthCheckPath: /healthcheck
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      # PORT is provided by Render automatically. Do NOT hardcode it.
      # Add your production secrets in the Render dashboard, or mount from .env.prod if using private repo.
      # Examples (uncomment and set via dashboard):
      # - key: DISCORD_TOKEN
      #   sync: false
      # - key: VIRUSTOTAL_API_KEY
      #   sync: false
      # - key: HF_API_TOKEN
      #   sync: false
      # - key: DATABASE_URL
      #   sync: false
      # - key: DESKTOP_RESTART_TOKEN
      #   sync: false
      # - key: DESKTOP_STATUS_SECRET
      #   sync: false
    # Optional scaling / plan settings:
    # plan: free
    # numInstances: 1
    # region: oregon
