services:
  - type: web
    name: satpambot-free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: RUN_BOT
        value: "1"
      - key: SOCKETIO_ASYNC_MODE
        value: threading
      - key: DISABLE_EVENTLET
        value: "1"
