services:
  - type: web
    name: satpambot-bot
    env: python
    rootDirectory: bot
    buildCommand: pip install -r requirements.txt
    startCommand: MODE=botmini python main.py
    autoDeploy: false

  - type: web
    name: satpambot-dashboard
    env: python
    rootDirectory: dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:app" --bind 0.0.0.0:$PORT --workers 2 --threads 4
    autoDeploy: false
