services:
  - type: web
    name: satpambot-free
    env: python
    buildCommand: |
      chmod +x scripts/build_render.sh
      ./scripts/build_render.sh
    startCommand: python main.py
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
