# Optional stricter Ruff profile (rename to ruff.toml when ready)
line-length = 120
target-version = "py312"
[lint]
select = ["E","F","I"]
ignore = ["E501","E402","E701","E702","E722","E741","F401","F403","F405","F841"]
