import json, os
fn = 'satpambot_config.local.json' if os.path.exists('satpambot_config.local.json') else 'local.json'
d = json.load(open(fn, encoding='utf-8'))
keys = [
  "PHASH_DB_PATH","PHASH_INDEX_LOG_CHANNEL_ID","PHASH_INDEX_THREAD_NAMES","PHASH_INDEX_THREAD_IDS",
  "PHASH_INDEX_BACKFILL_DAYS","PHASH_INDEX_SCAN_INTERVAL",
  "PHISH_ENFORCE_MODE","PHISH_STRONG_DISTANCE","PHISH_MODERATE_DISTANCE","PHISH_MIN_LABELED_DUPLICATES",
  "PHISH_ACTION_STRONG","PHISH_ACTION_MODERATE","PHISH_DELETE_MESSAGE_DAYS",
  "PHISH_BAN_REASON_PRESET","PHISH_BAN_REASON_SUFFIX","PHISH_MIME_SNIFF_ENABLE",
  "COGS_FORCE_ENABLE","STATUS_EDIT_WINDOW_SEC","STATUS_COALESCE_TITLES"
]
for k in keys:
    print(f"{k} = {d.get(k)}")
