#!/usr/bin/env python
"""
Hotfix legacy OpenAI usage:
- Ensure adapter at satpambot/ai/openai_v1_adapter.py
- Optionally patch 'openai.ChatCompletion.create(' -> 'chat_completion_create('
"""
import os, sys, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
ADAPTER_PATH = ROOT / 'satpambot' / 'ai' / 'openai_v1_adapter.py'

ADAPTER_SNIPPET = """# Auto-generated by scripts/apply_hotfixes.py
from __future__ import annotations
import os
try:
    from openai import OpenAI
except Exception:
    OpenAI = None  # type: ignore
_client = None
def _get_client():
    global _client
    if _client is None:
        if OpenAI is None:
            raise RuntimeError("openai SDK 1.x not installed. Install with: pip install 'openai>=1,<2'")
        _client = OpenAI(api_key=os.environ.get('OPENAI_API_KEY'))
    return _client
def chat_completion_create(*, model: str, messages, **kwargs):
    client = _get_client()
    stream = bool(kwargs.pop('stream', False))
    if stream:
        return client.chat.completions.create(model=model, messages=messages, stream=True, **kwargs)
    return client.chat.completions.create(model=model, messages=messages, **kwargs)
"""
PATCH_MARK = '# [apply_hotfixes] adapter-import'

def ensure_adapter():
    ADAPTER_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not ADAPTER_PATH.exists():
        ADAPTER_PATH.write_text(ADAPTER_SNIPPET, encoding='utf-8')
        print('[apply_hotfixes] wrote', ADAPTER_PATH)
    else:
        print('[apply_hotfixes] adapter exists:', ADAPTER_PATH)

def patch_callsites():
    changed = 0
    for p in ROOT.rglob('*.py'):
        pp = str(p).replace('\\','/')
        if '/venv/' in pp or '/.venv/' in pp or '/site-packages/' in pp or p.name == 'openai_v1_adapter.py':
            continue
        try:
            src = p.read_text(encoding='utf-8')
        except Exception:
            continue
        if 'openai.ChatCompletion.create(' not in src:
            continue
        new_src = src
        if 'from satpambot.ai.openai_v1_adapter import chat_completion_create' not in new_src:
            lines = new_src.splitlines()
            inserted = False
            for i, line in enumerate(lines[:50]):
                if line.startswith('import ') or line.startswith('from '):
                    continue
                lines.insert(i, 'from satpambot.ai.openai_v1_adapter import chat_completion_create  ' + PATCH_MARK)
                new_src = '\n'.join(lines)
                inserted = True
                break
            if not inserted:
                new_src = 'from satpambot.ai.openai_v1_adapter import chat_completion_create  ' + PATCH_MARK + '\n' + new_src
        new_src = new_src.replace('openai.ChatCompletion.create(', 'chat_completion_create(')
        if new_src != src:
            p.write_text(new_src, encoding='utf-8')
            changed += 1
            print('[apply_hotfixes] patched:', p)
    print(f'[apply_hotfixes] callsites patched: {changed}')

def main():
    ensure_adapter()
    patch_callsites()
    print('[apply_hotfixes] done.')
if __name__ == '__main__':
    main()
