name: Deploy Bot (Render)
on:
  push:
    branches: [ main ]
    paths:
      - 'bot/**'
      - '.github/workflows/deploy-bot.yml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: { group: render-bot, cancel-in-progress: true }
    steps:
      - name: Trigger Render deploy (bot)
        env: { HOOK: ${{ secrets.RENDER_BOT_DEPLOY_HOOK }} }
        run: |
          test -n "$HOOK" || { echo "Missing RENDER_BOT_DEPLOY_HOOK"; exit 1; }
          curl -fsSL -X POST "$HOOK"
